// Auto-generated from routeTree.gen.ts — do not edit manually.
// Run `bun run build:sw` to update.
export type AppRoute =
    | '/about'
    | '/design'
    | '/landing-page'
    | '/learning-tool'
    | '/sign-up'
    | '/app/changelog'
    | '/app/dashboard'
    | '/app/login'
    | '/app/logout'
    | '/app/settings'
    | '/app/settle'
    | '/app'
    | '/app/community/electricity-markets'
    | '/app/community/leaderboards'
    | '/app/community/map'
    | '/app/community/messages'
    | '/app/community/resource-market'
    | '/app/facilities/extraction'
    | '/app/facilities/functional'
    | '/app/facilities/manage'
    | '/app/facilities/power'
    | '/app/facilities/power-priorities'
    | '/app/facilities/storage'
    | '/app/facilities/technology'
    | '/app/internal/icons'
    | '/app/internal/typography'
    | '/app/overviews/cash-flow'
    | '/app/overviews/electricity-markets'
    | '/app/overviews/emissions'
    | '/app/overviews/power'
    | '/app/overviews/resources'
    | '/app/overviews/storage'
    | '/app/wiki/$slug'
    | '/app/wiki';
