aerodynamics:
  affected_facilities:
  - windmill
  - onshore_wind_turbine
  - offshore_wind_turbine
  base_construction_energy: 60000000.0
  base_construction_pollution: 0.0
  base_construction_time: 216000.0
  base_price: 84000
  description: Aerodynamics is the study of the motion of air and other gases.
  name: Aerodynamics
  price_factor: 1.15
  price_multiplier: 1.5
  prod_factor: 1.2
  requirements:
    laboratory: 3
    physics: 3
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172719&
building_technology:
  affected_facilities: []
  base_construction_energy: 16000000.0
  base_construction_pollution: 0.0
  base_construction_time: 144000.0
  base_price: 56000
  description: Building Technology enables more efficient construction of 
    facilities.
  name: Building Technology
  price_multiplier: 1.3
  requirements:
    laboratory: 1
    transport_technology: -2
  time_factor: 0.9
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172899&
chemistry:
  affected_facilities:
  - hydrogen_storage
  - lithium_ion_batteries
  - solid_state_batteries
  base_construction_energy: 40000000.0
  base_construction_pollution: 0.0
  base_construction_time: 144000.0
  base_price: 60000
  description: Chemistry is the study of matter and the changes it undergoes.
  inefficiency_factor: 0.9
  name: Chemistry
  price_factor: 1.25
  price_multiplier: 1.4
  requirements:
    laboratory: 3
    physics: -1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=174071&
civil_engineering:
  affected_facilities:
  - small_water_dam
  - large_water_dam
  - small_pumped_hydro
  - large_pumped_hydro
  base_construction_energy: 16000000.0
  base_construction_pollution: 0.0
  base_construction_time: 72000.0
  base_price: 28000
  capacity_factor: 1.15
  description: Civil Engineering is the branch of engineering for large 
    infrastructure projects.
  name: Civil Engineering
  price_factor: 1.2
  price_multiplier: 1.2
  prod_factor: 1.2
  requirements:
    building_technology: 2
    laboratory: 3
    mathematics: 2
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173564&
materials:
  affected_facilities:
  - onshore_wind_turbine
  - offshore_wind_turbine
  - PV_solar
  - lithium_ion_batteries
  - solid_state_batteries
  base_construction_energy: 48000000.0
  base_construction_pollution: 0.0
  base_construction_time: 216000.0
  base_price: 84000
  construction_energy_factor: 0.9
  description: Materials sciences are essential for the development of new 
    improved materials.
  name: Materials
  price_factor: 0.9
  price_multiplier: 1.4
  requirements:
    chemistry: 0
    laboratory: 2
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2024S&ansicht=ALLE&lerneinheitId=178386&
mathematics:
  affected_facilities: []
  base_construction_energy: 5000000.0
  base_construction_pollution: 0.0
  base_construction_time: 90000.0
  base_price: 36000
  description: Mathematics is a prerequisite for many other technologies.
  name: Mathematics
  price_multiplier: 1.3
  requirements:
    laboratory: 1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173657&
mechanical_engineering:
  affected_facilities:
  - steam_engine
  - watermill
  - coal_burner
  - gas_burner
  - combined_cycle
  - molten_salt
  base_construction_energy: 5000000.0
  base_construction_pollution: 0.0
  base_construction_time: 90000.0
  base_price: 36000
  description: Mechanical Engineering is the branch of engineering for machines 
    and mechanical systems.
  name: Mechanical Engineering
  price_factor: 1.15
  price_multiplier: 1.3
  prod_factor: 1.2
  requirements:
    laboratory: 1
    mathematics: 1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172711&
mineral_extraction:
  affected_facilities:
  - coal_mine
  - gas_drilling_site
  - uranium_mine
  base_construction_energy: 8000000.0
  base_construction_pollution: 0.0
  base_construction_time: 72000.0
  base_price: 32000
  description: Mineral Extraction improves the efficiency of the extraction of 
    natural resources.
  energy_factor: 0.25
  extract_factor: 0.3
  name: Mineral Extraction
  pollution_factor: 0.05
  price_factor: 1.2
  price_multiplier: 1.4
  requirements:
    laboratory: 1
    mathematics: 1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173723&
nuclear_engineering:
  affected_facilities:
  - nuclear_reactor
  - nuclear_reactor_gen4
  base_construction_energy: 108000000.0
  base_construction_pollution: 0.0
  base_construction_time: 324000.0
  base_price: 140000
  description: Nuclear Engineering is the branch of engineering for nuclear 
    power plants.
  name: Nuclear Engineering
  price_factor: 1.2
  price_multiplier: 1.5
  prod_factor: 1.25
  requirements:
    laboratory: 4
    mechanical_engineering: 3
    physics: 3
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172874&
physics:
  affected_facilities:
  - CSP_solar
  - PV_solar
  - hydrogen_storage
  - lithium_ion_batteries
  - solid_state_batteries
  base_construction_energy: 5000000.0
  base_construction_pollution: 0.0
  base_construction_time: 90000.0
  base_price: 36000
  description: Physics is the study of matter, energy, and the fundamental 
    forces of nature.
  name: Physics
  price_factor: 1.15
  price_multiplier: 1.3
  prod_factor: 1.2
  requirements:
    chemistry: -2
    laboratory: 1
    mathematics: 1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2024S&ansicht=ALLE&lerneinheitId=177068&
thermodynamics:
  affected_facilities:
  - steam_engine
  - coal_burner
  - gas_burner
  - combined_cycle
  - nuclear_reactor
  - nuclear_reactor_gen4
  - molten_salt
  base_construction_energy: 5000000.0
  base_construction_pollution: 0.0
  base_construction_time: 90000.0
  base_price: 36000
  description: Thermodynamics is the study of heat and energy transfer in 
    systems.
  efficiency_factor: 1.081081081081081
  name: Thermodynamics
  price_multiplier: 1.3
  requirements:
    laboratory: 1
    mathematics: 1
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173159&
transport_technology:
  affected_facilities: []
  base_construction_energy: 24000000.0
  base_construction_pollution: 0.0
  base_construction_time: 144000.0
  base_price: 56000
  description: Transport Technology enables more efficient shipping of natural 
    resources.
  energy_factor: 1.035
  name: Transport Technology
  price_multiplier: 1.4
  requirements:
    laboratory: 2
    mechanical_engineering: 1
  time_factor: 0.9
  wikipedia_link: 
    https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172788&
