/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes-lobby/__root'
import { Route as SignupRouteImport } from './routes-lobby/signup'
import { Route as RecapFingerprintPrototypeRouteImport } from './routes-lobby/recap-fingerprint-prototype'
import { Route as LogoutRouteImport } from './routes-lobby/logout'
import { Route as LoginRouteImport } from './routes-lobby/login'
import { Route as AccountRouteImport } from './routes-lobby/account'
import { Route as IndexRouteImport } from './routes-lobby/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapFingerprintPrototypeRoute =
  RecapFingerprintPrototypeRouteImport.update({
    id: '/recap-fingerprint-prototype',
    path: '/recap-fingerprint-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recap-fingerprint-prototype': typeof RecapFingerprintPrototypeRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recap-fingerprint-prototype': typeof RecapFingerprintPrototypeRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/recap-fingerprint-prototype': typeof RecapFingerprintPrototypeRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/logout'
    | '/recap-fingerprint-prototype'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/logout'
    | '/recap-fingerprint-prototype'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/logout'
    | '/recap-fingerprint-prototype'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RecapFingerprintPrototypeRoute: typeof RecapFingerprintPrototypeRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap-fingerprint-prototype': {
      id: '/recap-fingerprint-prototype'
      path: '/recap-fingerprint-prototype'
      fullPath: '/recap-fingerprint-prototype'
      preLoaderRoute: typeof RecapFingerprintPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RecapFingerprintPrototypeRoute: RecapFingerprintPrototypeRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
