/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LearningToolRouteImport } from './routes/learning-tool'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RouteRouteImport } from './routes/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettleRouteImport } from './routes/app/settle'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppLogoutRouteImport } from './routes/app/logout'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppChangelogRouteImport } from './routes/app/changelog'
import { Route as AppWikiIndexRouteImport } from './routes/app/wiki/index'
import { Route as AppWikiSlugRouteImport } from './routes/app/wiki/$slug'
import { Route as AppOverviewsStorageRouteImport } from './routes/app/overviews/storage'
import { Route as AppOverviewsResourcesRouteImport } from './routes/app/overviews/resources'
import { Route as AppOverviewsPowerRouteImport } from './routes/app/overviews/power'
import { Route as AppOverviewsEmissionsRouteImport } from './routes/app/overviews/emissions'
import { Route as AppOverviewsElectricityMarketsRouteImport } from './routes/app/overviews/electricity-markets'
import { Route as AppOverviewsCashFlowRouteImport } from './routes/app/overviews/cash-flow'
import { Route as AppInternalTypographyRouteImport } from './routes/app/internal/typography'
import { Route as AppInternalIconsRouteImport } from './routes/app/internal/icons'
import { Route as AppInternalDesignRouteImport } from './routes/app/internal/design'
import { Route as AppFacilitiesTechnologyRouteImport } from './routes/app/facilities/technology'
import { Route as AppFacilitiesStorageRouteImport } from './routes/app/facilities/storage'
import { Route as AppFacilitiesPowerPrioritiesRouteImport } from './routes/app/facilities/power-priorities'
import { Route as AppFacilitiesPowerRouteImport } from './routes/app/facilities/power'
import { Route as AppFacilitiesManageRouteImport } from './routes/app/facilities/manage'
import { Route as AppFacilitiesFunctionalRouteImport } from './routes/app/facilities/functional'
import { Route as AppFacilitiesExtractionRouteImport } from './routes/app/facilities/extraction'
import { Route as AppCommunityResourceMarketRouteImport } from './routes/app/community/resource-market'
import { Route as AppCommunityMessagesRouteImport } from './routes/app/community/messages'
import { Route as AppCommunityMapRouteImport } from './routes/app/community/map'
import { Route as AppCommunityLeaderboardsRouteImport } from './routes/app/community/leaderboards'
import { Route as AppCommunityElectricityMarketsRouteImport } from './routes/app/community/electricity-markets'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningToolRoute = LearningToolRouteImport.update({
  id: '/learning-tool',
  path: '/learning-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettleRoute = AppSettleRouteImport.update({
  id: '/app/settle',
  path: '/app/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/app/logout',
  path: '/app/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/app/changelog',
  path: '/app/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWikiIndexRoute = AppWikiIndexRouteImport.update({
  id: '/app/wiki/',
  path: '/app/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWikiSlugRoute = AppWikiSlugRouteImport.update({
  id: '/app/wiki/$slug',
  path: '/app/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewsStorageRoute = AppOverviewsStorageRouteImport.update({
  id: '/app/overviews/storage',
  path: '/app/overviews/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewsResourcesRoute = AppOverviewsResourcesRouteImport.update({
  id: '/app/overviews/resources',
  path: '/app/overviews/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewsPowerRoute = AppOverviewsPowerRouteImport.update({
  id: '/app/overviews/power',
  path: '/app/overviews/power',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewsEmissionsRoute = AppOverviewsEmissionsRouteImport.update({
  id: '/app/overviews/emissions',
  path: '/app/overviews/emissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewsElectricityMarketsRoute =
  AppOverviewsElectricityMarketsRouteImport.update({
    id: '/app/overviews/electricity-markets',
    path: '/app/overviews/electricity-markets',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOverviewsCashFlowRoute = AppOverviewsCashFlowRouteImport.update({
  id: '/app/overviews/cash-flow',
  path: '/app/overviews/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternalTypographyRoute = AppInternalTypographyRouteImport.update({
  id: '/app/internal/typography',
  path: '/app/internal/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternalIconsRoute = AppInternalIconsRouteImport.update({
  id: '/app/internal/icons',
  path: '/app/internal/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternalDesignRoute = AppInternalDesignRouteImport.update({
  id: '/app/internal/design',
  path: '/app/internal/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesTechnologyRoute = AppFacilitiesTechnologyRouteImport.update({
  id: '/app/facilities/technology',
  path: '/app/facilities/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesStorageRoute = AppFacilitiesStorageRouteImport.update({
  id: '/app/facilities/storage',
  path: '/app/facilities/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesPowerPrioritiesRoute =
  AppFacilitiesPowerPrioritiesRouteImport.update({
    id: '/app/facilities/power-priorities',
    path: '/app/facilities/power-priorities',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppFacilitiesPowerRoute = AppFacilitiesPowerRouteImport.update({
  id: '/app/facilities/power',
  path: '/app/facilities/power',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesManageRoute = AppFacilitiesManageRouteImport.update({
  id: '/app/facilities/manage',
  path: '/app/facilities/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesFunctionalRoute = AppFacilitiesFunctionalRouteImport.update({
  id: '/app/facilities/functional',
  path: '/app/facilities/functional',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFacilitiesExtractionRoute = AppFacilitiesExtractionRouteImport.update({
  id: '/app/facilities/extraction',
  path: '/app/facilities/extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityResourceMarketRoute =
  AppCommunityResourceMarketRouteImport.update({
    id: '/app/community/resource-market',
    path: '/app/community/resource-market',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityMessagesRoute = AppCommunityMessagesRouteImport.update({
  id: '/app/community/messages',
  path: '/app/community/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityMapRoute = AppCommunityMapRouteImport.update({
  id: '/app/community/map',
  path: '/app/community/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityLeaderboardsRoute =
  AppCommunityLeaderboardsRouteImport.update({
    id: '/app/community/leaderboards',
    path: '/app/community/leaderboards',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppCommunityElectricityMarketsRoute =
  AppCommunityElectricityMarketsRouteImport.update({
    id: '/app/community/electricity-markets',
    path: '/app/community/electricity-markets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/landing-page': typeof LandingPageRoute
  '/learning-tool': typeof LearningToolRoute
  '/sign-up': typeof SignUpRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/logout': typeof AppLogoutRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settle': typeof AppSettleRoute
  '/app': typeof AppIndexRoute
  '/app/community/electricity-markets': typeof AppCommunityElectricityMarketsRoute
  '/app/community/leaderboards': typeof AppCommunityLeaderboardsRoute
  '/app/community/map': typeof AppCommunityMapRoute
  '/app/community/messages': typeof AppCommunityMessagesRoute
  '/app/community/resource-market': typeof AppCommunityResourceMarketRoute
  '/app/facilities/extraction': typeof AppFacilitiesExtractionRoute
  '/app/facilities/functional': typeof AppFacilitiesFunctionalRoute
  '/app/facilities/manage': typeof AppFacilitiesManageRoute
  '/app/facilities/power': typeof AppFacilitiesPowerRoute
  '/app/facilities/power-priorities': typeof AppFacilitiesPowerPrioritiesRoute
  '/app/facilities/storage': typeof AppFacilitiesStorageRoute
  '/app/facilities/technology': typeof AppFacilitiesTechnologyRoute
  '/app/internal/design': typeof AppInternalDesignRoute
  '/app/internal/icons': typeof AppInternalIconsRoute
  '/app/internal/typography': typeof AppInternalTypographyRoute
  '/app/overviews/cash-flow': typeof AppOverviewsCashFlowRoute
  '/app/overviews/electricity-markets': typeof AppOverviewsElectricityMarketsRoute
  '/app/overviews/emissions': typeof AppOverviewsEmissionsRoute
  '/app/overviews/power': typeof AppOverviewsPowerRoute
  '/app/overviews/resources': typeof AppOverviewsResourcesRoute
  '/app/overviews/storage': typeof AppOverviewsStorageRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki': typeof AppWikiIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/landing-page': typeof LandingPageRoute
  '/learning-tool': typeof LearningToolRoute
  '/sign-up': typeof SignUpRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/logout': typeof AppLogoutRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settle': typeof AppSettleRoute
  '/app': typeof AppIndexRoute
  '/app/community/electricity-markets': typeof AppCommunityElectricityMarketsRoute
  '/app/community/leaderboards': typeof AppCommunityLeaderboardsRoute
  '/app/community/map': typeof AppCommunityMapRoute
  '/app/community/messages': typeof AppCommunityMessagesRoute
  '/app/community/resource-market': typeof AppCommunityResourceMarketRoute
  '/app/facilities/extraction': typeof AppFacilitiesExtractionRoute
  '/app/facilities/functional': typeof AppFacilitiesFunctionalRoute
  '/app/facilities/manage': typeof AppFacilitiesManageRoute
  '/app/facilities/power': typeof AppFacilitiesPowerRoute
  '/app/facilities/power-priorities': typeof AppFacilitiesPowerPrioritiesRoute
  '/app/facilities/storage': typeof AppFacilitiesStorageRoute
  '/app/facilities/technology': typeof AppFacilitiesTechnologyRoute
  '/app/internal/design': typeof AppInternalDesignRoute
  '/app/internal/icons': typeof AppInternalIconsRoute
  '/app/internal/typography': typeof AppInternalTypographyRoute
  '/app/overviews/cash-flow': typeof AppOverviewsCashFlowRoute
  '/app/overviews/electricity-markets': typeof AppOverviewsElectricityMarketsRoute
  '/app/overviews/emissions': typeof AppOverviewsEmissionsRoute
  '/app/overviews/power': typeof AppOverviewsPowerRoute
  '/app/overviews/resources': typeof AppOverviewsResourcesRoute
  '/app/overviews/storage': typeof AppOverviewsStorageRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki': typeof AppWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/about': typeof AboutRoute
  '/landing-page': typeof LandingPageRoute
  '/learning-tool': typeof LearningToolRoute
  '/sign-up': typeof SignUpRoute
  '/app/changelog': typeof AppChangelogRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/login': typeof AppLoginRoute
  '/app/logout': typeof AppLogoutRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settle': typeof AppSettleRoute
  '/app/': typeof AppIndexRoute
  '/app/community/electricity-markets': typeof AppCommunityElectricityMarketsRoute
  '/app/community/leaderboards': typeof AppCommunityLeaderboardsRoute
  '/app/community/map': typeof AppCommunityMapRoute
  '/app/community/messages': typeof AppCommunityMessagesRoute
  '/app/community/resource-market': typeof AppCommunityResourceMarketRoute
  '/app/facilities/extraction': typeof AppFacilitiesExtractionRoute
  '/app/facilities/functional': typeof AppFacilitiesFunctionalRoute
  '/app/facilities/manage': typeof AppFacilitiesManageRoute
  '/app/facilities/power': typeof AppFacilitiesPowerRoute
  '/app/facilities/power-priorities': typeof AppFacilitiesPowerPrioritiesRoute
  '/app/facilities/storage': typeof AppFacilitiesStorageRoute
  '/app/facilities/technology': typeof AppFacilitiesTechnologyRoute
  '/app/internal/design': typeof AppInternalDesignRoute
  '/app/internal/icons': typeof AppInternalIconsRoute
  '/app/internal/typography': typeof AppInternalTypographyRoute
  '/app/overviews/cash-flow': typeof AppOverviewsCashFlowRoute
  '/app/overviews/electricity-markets': typeof AppOverviewsElectricityMarketsRoute
  '/app/overviews/emissions': typeof AppOverviewsEmissionsRoute
  '/app/overviews/power': typeof AppOverviewsPowerRoute
  '/app/overviews/resources': typeof AppOverviewsResourcesRoute
  '/app/overviews/storage': typeof AppOverviewsStorageRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/': typeof AppWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/landing-page'
    | '/learning-tool'
    | '/sign-up'
    | '/app/changelog'
    | '/app/dashboard'
    | '/app/login'
    | '/app/logout'
    | '/app/settings'
    | '/app/settle'
    | '/app'
    | '/app/community/electricity-markets'
    | '/app/community/leaderboards'
    | '/app/community/map'
    | '/app/community/messages'
    | '/app/community/resource-market'
    | '/app/facilities/extraction'
    | '/app/facilities/functional'
    | '/app/facilities/manage'
    | '/app/facilities/power'
    | '/app/facilities/power-priorities'
    | '/app/facilities/storage'
    | '/app/facilities/technology'
    | '/app/internal/design'
    | '/app/internal/icons'
    | '/app/internal/typography'
    | '/app/overviews/cash-flow'
    | '/app/overviews/electricity-markets'
    | '/app/overviews/emissions'
    | '/app/overviews/power'
    | '/app/overviews/resources'
    | '/app/overviews/storage'
    | '/app/wiki/$slug'
    | '/app/wiki'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/landing-page'
    | '/learning-tool'
    | '/sign-up'
    | '/app/changelog'
    | '/app/dashboard'
    | '/app/login'
    | '/app/logout'
    | '/app/settings'
    | '/app/settle'
    | '/app'
    | '/app/community/electricity-markets'
    | '/app/community/leaderboards'
    | '/app/community/map'
    | '/app/community/messages'
    | '/app/community/resource-market'
    | '/app/facilities/extraction'
    | '/app/facilities/functional'
    | '/app/facilities/manage'
    | '/app/facilities/power'
    | '/app/facilities/power-priorities'
    | '/app/facilities/storage'
    | '/app/facilities/technology'
    | '/app/internal/design'
    | '/app/internal/icons'
    | '/app/internal/typography'
    | '/app/overviews/cash-flow'
    | '/app/overviews/electricity-markets'
    | '/app/overviews/emissions'
    | '/app/overviews/power'
    | '/app/overviews/resources'
    | '/app/overviews/storage'
    | '/app/wiki/$slug'
    | '/app/wiki'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/landing-page'
    | '/learning-tool'
    | '/sign-up'
    | '/app/changelog'
    | '/app/dashboard'
    | '/app/login'
    | '/app/logout'
    | '/app/settings'
    | '/app/settle'
    | '/app/'
    | '/app/community/electricity-markets'
    | '/app/community/leaderboards'
    | '/app/community/map'
    | '/app/community/messages'
    | '/app/community/resource-market'
    | '/app/facilities/extraction'
    | '/app/facilities/functional'
    | '/app/facilities/manage'
    | '/app/facilities/power'
    | '/app/facilities/power-priorities'
    | '/app/facilities/storage'
    | '/app/facilities/technology'
    | '/app/internal/design'
    | '/app/internal/icons'
    | '/app/internal/typography'
    | '/app/overviews/cash-flow'
    | '/app/overviews/electricity-markets'
    | '/app/overviews/emissions'
    | '/app/overviews/power'
    | '/app/overviews/resources'
    | '/app/overviews/storage'
    | '/app/wiki/$slug'
    | '/app/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AboutRoute: typeof AboutRoute
  LandingPageRoute: typeof LandingPageRoute
  LearningToolRoute: typeof LearningToolRoute
  SignUpRoute: typeof SignUpRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoginRoute: typeof AppLoginRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSettleRoute: typeof AppSettleRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunityElectricityMarketsRoute: typeof AppCommunityElectricityMarketsRoute
  AppCommunityLeaderboardsRoute: typeof AppCommunityLeaderboardsRoute
  AppCommunityMapRoute: typeof AppCommunityMapRoute
  AppCommunityMessagesRoute: typeof AppCommunityMessagesRoute
  AppCommunityResourceMarketRoute: typeof AppCommunityResourceMarketRoute
  AppFacilitiesExtractionRoute: typeof AppFacilitiesExtractionRoute
  AppFacilitiesFunctionalRoute: typeof AppFacilitiesFunctionalRoute
  AppFacilitiesManageRoute: typeof AppFacilitiesManageRoute
  AppFacilitiesPowerRoute: typeof AppFacilitiesPowerRoute
  AppFacilitiesPowerPrioritiesRoute: typeof AppFacilitiesPowerPrioritiesRoute
  AppFacilitiesStorageRoute: typeof AppFacilitiesStorageRoute
  AppFacilitiesTechnologyRoute: typeof AppFacilitiesTechnologyRoute
  AppInternalDesignRoute: typeof AppInternalDesignRoute
  AppInternalIconsRoute: typeof AppInternalIconsRoute
  AppInternalTypographyRoute: typeof AppInternalTypographyRoute
  AppOverviewsCashFlowRoute: typeof AppOverviewsCashFlowRoute
  AppOverviewsElectricityMarketsRoute: typeof AppOverviewsElectricityMarketsRoute
  AppOverviewsEmissionsRoute: typeof AppOverviewsEmissionsRoute
  AppOverviewsPowerRoute: typeof AppOverviewsPowerRoute
  AppOverviewsResourcesRoute: typeof AppOverviewsResourcesRoute
  AppOverviewsStorageRoute: typeof AppOverviewsStorageRoute
  AppWikiSlugRoute: typeof AppWikiSlugRoute
  AppWikiIndexRoute: typeof AppWikiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-tool': {
      id: '/learning-tool'
      path: '/learning-tool'
      fullPath: '/learning-tool'
      preLoaderRoute: typeof LearningToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settle': {
      id: '/app/settle'
      path: '/app/settle'
      fullPath: '/app/settle'
      preLoaderRoute: typeof AppSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/logout': {
      id: '/app/logout'
      path: '/app/logout'
      fullPath: '/app/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/changelog': {
      id: '/app/changelog'
      path: '/app/changelog'
      fullPath: '/app/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wiki/': {
      id: '/app/wiki/'
      path: '/app/wiki'
      fullPath: '/app/wiki'
      preLoaderRoute: typeof AppWikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wiki/$slug': {
      id: '/app/wiki/$slug'
      path: '/app/wiki/$slug'
      fullPath: '/app/wiki/$slug'
      preLoaderRoute: typeof AppWikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/storage': {
      id: '/app/overviews/storage'
      path: '/app/overviews/storage'
      fullPath: '/app/overviews/storage'
      preLoaderRoute: typeof AppOverviewsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/resources': {
      id: '/app/overviews/resources'
      path: '/app/overviews/resources'
      fullPath: '/app/overviews/resources'
      preLoaderRoute: typeof AppOverviewsResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/power': {
      id: '/app/overviews/power'
      path: '/app/overviews/power'
      fullPath: '/app/overviews/power'
      preLoaderRoute: typeof AppOverviewsPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/emissions': {
      id: '/app/overviews/emissions'
      path: '/app/overviews/emissions'
      fullPath: '/app/overviews/emissions'
      preLoaderRoute: typeof AppOverviewsEmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/electricity-markets': {
      id: '/app/overviews/electricity-markets'
      path: '/app/overviews/electricity-markets'
      fullPath: '/app/overviews/electricity-markets'
      preLoaderRoute: typeof AppOverviewsElectricityMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overviews/cash-flow': {
      id: '/app/overviews/cash-flow'
      path: '/app/overviews/cash-flow'
      fullPath: '/app/overviews/cash-flow'
      preLoaderRoute: typeof AppOverviewsCashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internal/typography': {
      id: '/app/internal/typography'
      path: '/app/internal/typography'
      fullPath: '/app/internal/typography'
      preLoaderRoute: typeof AppInternalTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internal/icons': {
      id: '/app/internal/icons'
      path: '/app/internal/icons'
      fullPath: '/app/internal/icons'
      preLoaderRoute: typeof AppInternalIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internal/design': {
      id: '/app/internal/design'
      path: '/app/internal/design'
      fullPath: '/app/internal/design'
      preLoaderRoute: typeof AppInternalDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/technology': {
      id: '/app/facilities/technology'
      path: '/app/facilities/technology'
      fullPath: '/app/facilities/technology'
      preLoaderRoute: typeof AppFacilitiesTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/storage': {
      id: '/app/facilities/storage'
      path: '/app/facilities/storage'
      fullPath: '/app/facilities/storage'
      preLoaderRoute: typeof AppFacilitiesStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/power-priorities': {
      id: '/app/facilities/power-priorities'
      path: '/app/facilities/power-priorities'
      fullPath: '/app/facilities/power-priorities'
      preLoaderRoute: typeof AppFacilitiesPowerPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/power': {
      id: '/app/facilities/power'
      path: '/app/facilities/power'
      fullPath: '/app/facilities/power'
      preLoaderRoute: typeof AppFacilitiesPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/manage': {
      id: '/app/facilities/manage'
      path: '/app/facilities/manage'
      fullPath: '/app/facilities/manage'
      preLoaderRoute: typeof AppFacilitiesManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/functional': {
      id: '/app/facilities/functional'
      path: '/app/facilities/functional'
      fullPath: '/app/facilities/functional'
      preLoaderRoute: typeof AppFacilitiesFunctionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/facilities/extraction': {
      id: '/app/facilities/extraction'
      path: '/app/facilities/extraction'
      fullPath: '/app/facilities/extraction'
      preLoaderRoute: typeof AppFacilitiesExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/resource-market': {
      id: '/app/community/resource-market'
      path: '/app/community/resource-market'
      fullPath: '/app/community/resource-market'
      preLoaderRoute: typeof AppCommunityResourceMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/messages': {
      id: '/app/community/messages'
      path: '/app/community/messages'
      fullPath: '/app/community/messages'
      preLoaderRoute: typeof AppCommunityMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/map': {
      id: '/app/community/map'
      path: '/app/community/map'
      fullPath: '/app/community/map'
      preLoaderRoute: typeof AppCommunityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/leaderboards': {
      id: '/app/community/leaderboards'
      path: '/app/community/leaderboards'
      fullPath: '/app/community/leaderboards'
      preLoaderRoute: typeof AppCommunityLeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/electricity-markets': {
      id: '/app/community/electricity-markets'
      path: '/app/community/electricity-markets'
      fullPath: '/app/community/electricity-markets'
      preLoaderRoute: typeof AppCommunityElectricityMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AboutRoute: AboutRoute,
  LandingPageRoute: LandingPageRoute,
  LearningToolRoute: LearningToolRoute,
  SignUpRoute: SignUpRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLoginRoute: AppLoginRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSettleRoute: AppSettleRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunityElectricityMarketsRoute: AppCommunityElectricityMarketsRoute,
  AppCommunityLeaderboardsRoute: AppCommunityLeaderboardsRoute,
  AppCommunityMapRoute: AppCommunityMapRoute,
  AppCommunityMessagesRoute: AppCommunityMessagesRoute,
  AppCommunityResourceMarketRoute: AppCommunityResourceMarketRoute,
  AppFacilitiesExtractionRoute: AppFacilitiesExtractionRoute,
  AppFacilitiesFunctionalRoute: AppFacilitiesFunctionalRoute,
  AppFacilitiesManageRoute: AppFacilitiesManageRoute,
  AppFacilitiesPowerRoute: AppFacilitiesPowerRoute,
  AppFacilitiesPowerPrioritiesRoute: AppFacilitiesPowerPrioritiesRoute,
  AppFacilitiesStorageRoute: AppFacilitiesStorageRoute,
  AppFacilitiesTechnologyRoute: AppFacilitiesTechnologyRoute,
  AppInternalDesignRoute: AppInternalDesignRoute,
  AppInternalIconsRoute: AppInternalIconsRoute,
  AppInternalTypographyRoute: AppInternalTypographyRoute,
  AppOverviewsCashFlowRoute: AppOverviewsCashFlowRoute,
  AppOverviewsElectricityMarketsRoute: AppOverviewsElectricityMarketsRoute,
  AppOverviewsEmissionsRoute: AppOverviewsEmissionsRoute,
  AppOverviewsPowerRoute: AppOverviewsPowerRoute,
  AppOverviewsResourcesRoute: AppOverviewsResourcesRoute,
  AppOverviewsStorageRoute: AppOverviewsStorageRoute,
  AppWikiSlugRoute: AppWikiSlugRoute,
  AppWikiIndexRoute: AppWikiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
