"""
This file contains all the data needed for the game
"""

from .database.player import Player
import copy
from flask import current_app

const_config = {
    "assets": {
        "steam_engine": {
            "name": "Steam engine",
            "type": "Controllable",
            "image_extension": "png",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Steam_engine",
            "description": "The O&M costs of the steam engine are composed of 20% fixed costs and 80% variable costs.",
            "danger_description": "Risk of steam explosion",
        },
        "windmill": {
            "name": "Windmill",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The amount of electricity generated by the windmill will vary according to the strength of the wind.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Windmill",
            "danger_description": "Risk of structural failure in high winds",
        },
        "watermill": {
            "name": "Watermill",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The electricity output of the watermill relies on the flow rate of the river's water.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Watermill",
            "danger_description": "Risk of structural failure due to floods",
        },
        "coal_burner": {
            "name": "Coal burner",
            "type": "Controllable",
            "image_extension": "jpg",
            "description": "The coal burner consumes coal to produce electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Coal-fired_power_station",
        },
        "oil_burner": {
            "name": "Oil burner",
            "type": "Controllable",
            "image_extension": "jpg",
            "description": "The oil burner consumes oil to produce electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Fossil_fuel_power_station",
        },
        "gas_burner": {
            "name": "Gas burner",
            "type": "Controllable",
            "image_extension": "jpg",
            "description": "The gas burner consumes gas to produce electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Gas-fired_power_facility",
            "danger_description": "Risk of gas leaks",
        },
        "small_water_dam": {
            "name": "Small water dam",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The electricity output of the small water dam relies on the flow rate of the river's water.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Hydroelectricity",
            "danger_description": "Risk of structural failure due to floods",
        },
        "onshore_wind_turbine": {
            "name": "Onshore wind turbine",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The amount of electricity generated by the onshore wind turbine will vary according to the strength of the wind.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Wind_turbine",
            "danger_description": "Risk of structural failure in high winds",
        },
        "combined_cycle": {
            "name": "Combined cycle",
            "type": "Controllable",
            "image_extension": "png",
            "description": "The combined cycle power facility consumes coal and gas to produce electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Combined_cycle_power_facility",
            "danger_description": "Risk of gas leaks",
        },
        "nuclear_reactor": {
            "name": "Nuclear reactor",
            "type": "Controllable",
            "image_extension": "jpg",
            "description": "The nuclear power plant uses controlled nuclear fission to produce electricity from uranium.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Nuclear_power_facility",
            "danger_description": "Risk of reactor meltdown",
        },
        "large_water_dam": {
            "name": "Large water dam",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The electricity output of the large water dam relies on the flow rate of the river's water.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Hydroelectricity",
            "danger_description": "Risk of structural failure due to floods",
        },
        "CSP_solar": {
            "name": "Concentrated solar power",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The amount of electricity generated by the concentrated solar power plant will vary according to the level of irradiance.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Concentrated_solar_power",
        },
        "PV_solar": {
            "name": "Photovoltaics",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The amount of electricity generated by the photovoltaic pannels will vary according to the level of irradiance.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Photovoltaics",
        },
        "offshore_wind_turbine": {
            "name": "Offshore wind turbine",
            "type": "Renewable",
            "image_extension": "jpg",
            "description": "The amount of electricity generated by the offshore wind turbine will vary according to the strength of the wind.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Wind_turbine",
            "danger_description": "Risk of structural failure due to storms",
        },
        "nuclear_reactor_gen4": {
            "name": "4th generation nuclear",
            "type": "Controllable",
            "image_extension": "png",
            "description": "The 4th generation nuclear power plant uses controlled nuclear fission to produce electricity from natural uranium.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Generation_IV_reactor",
            "danger_description": "Risk of reactor meltdown",
        },
        "small_pumped_hydro": {
            "name": "Small pumped hydro",
            "type": "Storage",
            "image_extension": "png",
            "initial_efficiency": 0.75,
            "description": "The small pumped hydropower storage pumps water to a higher altitude to store energy.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Pumped-storage_hydroelectricity",
        },
        "compressed_air": {
            "name": "Compressed air",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.52,
            "description": "The compressed air storage facility stores mechanical energy in the form of compressed gas in the ground.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Compressed-air_energy_storage",
        },
        "molten_salt": {
            "name": "Molten salt",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.63,
            "description": "The Molten salt storage stores molten satl at high temperatures to be used for electricity producion.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Thermal_energy_storage",
        },
        "large_pumped_hydro": {
            "name": "Large pumped hydro",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.8,
            "description": "The large pumped hydropower storage pumps water to a higher altitude to store a large amount of energy.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Pumped-storage_hydroelectricity",
        },
        "hydrogen_storage": {
            "name": "Hydrogen hydrolysis",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.33,
            "description": "The hydrogen storage stores hydrogen that has been generated by electrolysys and can be transformed into electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Hydrogen_storage",
        },
        "lithium_ion_batteries": {
            "name": "Lithium-ion batteries",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.69,
            "description": "The lithium ion battery storage facility stores electricity with high efficiency.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Lithium-ion_battery",
        },
        "solid_state_batteries": {
            "name": "Solid state batteries",
            "type": "Storage",
            "image_extension": "jpg",
            "initial_efficiency": 0.79,
            "description": "The solid state battery storage facility stores electricity with high efficiency.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Solid-state_battery",
        },
        "laboratory": {
            "name": "Laboratory",
            "type": "Functional facility",
            "price multiplier": 1.5,
            "time factor": 0.9,
            "description": "The laboratory is needed to research Technologies.",
            "wikipedia_link": "",
        },
        "warehouse": {
            "name": "Warehouse",
            "type": "Functional facility",
            "price multiplier": 1.5,
            "capacity factor": 1.5,
            "description": "The warehouse stores physical resources.",
            "wikipedia_link": "",
        },
        "industry": {
            "name": "Industry",
            "type": "Functional facility",
            "price multiplier": 1.32,
            "power factor": 1.4,
            "income factor": 1.35,
            "description": "The industry generates revenue from energy. The Power consumption of the Industry varies daily and seasonally.",
            "wikipedia_link": "",
        },
        "carbon_capture": {
            "name": "Carbon capture",
            "type": "Functional facility",
            "price multiplier": 1.5,
            "absorbtion factor": 1.55,
            "power factor": 1.5,
            "description": "Carbon capture consumes energy to absorb and store CO2 underground.",
            "wikipedia_link": "",
        },
        "coal_mine": {
            "name": "Coal mine",
            "type": "Extraction facility",
            "extraction_rate": 0.000005,  # [fraction of total stock that can be extracted every minute by one mine]
            "description": "The coal mine extracts coal from the ground using electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Coal_mining",
        },
        "oil_field": {
            "name": "Oil field",
            "type": "Extraction facility",
            "extraction_rate": 0.00005,
            "description": "The oil field extracts oil from the ground using electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Extraction_of_petroleum",
        },
        "gas_drilling_site": {
            "name": "Gas drilling site",
            "type": "Extraction facility",
            "extraction_rate": 0.00004,
            "description": "The gas drilling site extracts gas from the ground using electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Natural_gas",
        },
        "uranium_mine": {
            "name": "Uranium mine",
            "type": "Extraction facility",
            "extraction_rate": 0.000005,
            "description": "The uranium mine extracts uranium from the ground using electricity.",
            "wikipedia_link": "https://en.wikipedia.org/wiki/Uranium_mining",
        },
        "mathematics": {
            "name": "Mathematics",
            "type": "Technology",
            "price multiplier": 1.3,
            "affected facilities": [],
            "description": "Mathematics is the fundamental tool of science.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173657&",
        },
        "mechanical_engineering": {
            "name": "Mechanical engineering",
            "type": "Technology",
            "price multiplier": 1.3,
            "price factor": 1.15,
            "prod factor": 1.2,
            "affected facilities": [
                "steam_engine",
                "watermill",
                "coal_burner",
                "oil_burner",
                "gas_burner",
                "combined_cycle",
                "compressed_air",
                "molten_salt",
            ],
            "description": "Mechanical engineering drives innovation in machine design and functionality.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172711&",
        },
        "thermodynamics": {
            "name": "Thermodynamics",
            "type": "Technology",
            "price multiplier": 1.3,
            "efficiency_factor": 1 / (1 - 0.075),
            "affected facilities": [
                "steam_engine",
                "coal_burner",
                "oil_burner",
                "gas_burner",
                "combined_cycle",
                "nuclear_reactor",
                "nuclear_reactor_gen4",
                "compressed_air",
                "molten_salt",
            ],
            "description": "Thermodynamics explores the dynamics of energy transfer and transformation.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173159&",
        },
        "physics": {
            "name": "Physics",
            "type": "Technology",
            "price multiplier": 1.3,
            "price factor": 1.15,
            "prod factor": 1.2,
            "affected facilities": [
                "CSP_solar",
                "PV_solar",
                "hydrogen_storage",
                "lithium_ion_batteries",
                "solid_state_batteries",
            ],
            "description": "Physics delves into the empirical exploration and comprehension of natural phenomena.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2024S&ansicht=ALLE&lerneinheitId=177068&",
        },
        "building_technology": {
            "name": "Building Technology",
            "type": "Technology",
            "price multiplier": 1.3,
            "time factor": 0.9,
            "affected facilities": [],  # (all power and storage facilites)
            "description": "Building technology enables more efficient construction of facilities.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172899&",
        },
        "mineral_extraction": {
            "name": "Mineral extraction",
            "type": "Technology",
            "price multiplier": 1.4,
            "price factor": 1.2,
            "extract factor": 1.30,
            "energy factor": 1.25,
            "pollution factor": 1.05,
            "affected facilities": [
                "coal_mine",
                "oil_field",
                "gas_drilling_site",
                "uranium_mine",
            ],
            "description": "Mineral extraction improves the extraction process of natural resources.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173723&",
        },
        "transport_technology": {
            "name": "Transport technology",
            "type": "Technology",
            "price multiplier": 1.4,
            "time factor": 0.9,
            "energy factor": 1.035,
            "affected facilities": [],
            "description": "Transport technology enables more efficient shipments of natural resources.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172788&",
        },
        "materials": {
            "name": "Materials",
            "type": "Technology",
            "price multiplier": 1.4,
            "price factor": 0.9,
            "construction energy factor": 0.9,
            "affected facilities": [
                "onshore_wind_turbine",
                "offshore_wind_turbine",
                "PV_solar",
                "lithium_ion_batteries",
                "solid_state_batteries",
            ],
            "description": "Material sciences are essential to discover and improve advanced materials.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2024S&ansicht=ALLE&lerneinheitId=178386&",
        },
        "civil_engineering": {
            "name": "Civil engineering",
            "type": "Technology",
            "price multiplier": 1.5,
            "price factor": 1.25,
            "prod factor": 1.15,
            "capacity factor": 1.05,
            "affected facilities": [
                "small_water_dam",
                "large_water_dam",
                "small_pumped_hydro",
                "large_pumped_hydro",
            ],
            "description": "Civil engineering enables the realization of large infrastructure projects.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=173564&",
        },
        "aerodynamics": {
            "name": "Aerodynamics",
            "type": "Technology",
            "price multiplier": 1.5,
            "price factor": 1.15,
            "prod factor": 1.2,
            "affected facilities": [
                "windmill",
                "lithium_ion_batteries",
                "solid_state_batteries",
            ],
            "description": "Aerodynamics studies the principles governing airflow.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172719&",
        },
        "chemistry": {
            "name": "Chemistry",
            "type": "Technology",
            "price multiplier": 1.4,
            "price factor": 1.25,
            "inefficiency_factor": 0.9,
            "affected facilities": [
                "hydrogen_storage",
                "lithium_ion_batteries",
                "solid_state_batteries",
            ],
            "description": "Chemistry unlocks the mysteries of molecular interactions and transformations.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=174071&",
        },
        "nuclear_engineering": {
            "name": "Nuclear engineering",
            "type": "Technology",
            "price multiplier": 1.5,
            "price factor": 1.2,
            "prod factor": 1.25,
            "affected facilities": [
                "nuclear_reactor",
                "nuclear_reactor_gen4",
            ],
            "description": "Nuclear engineering is used to improve nuclear power facilities.",
            "wikipedia_link": "https://www.vvz.ethz.ch/Vorlesungsverzeichnis/lerneinheit.view?lang=en&semkez=2023W&ansicht=ALLE&lerneinheitId=172874&",
        },
    }
}

# initial values of the game for each asset
var_config = {
    "assets": {
        "steam_engine": {
            "price": 10000,  # [¤]
            "power generation": 820000,  # [W]
            "construction time": 5400,  # [s]
            "construction power factor": 0.4,  # fraction of power gen during construction
            "construction pollution": 17520,  # [kg]
            "O&M cost": 0.8,  # [fraction of price per (day)]
            "consumed resource": {},  # [kg/MWh]
            "pollution": 988,  # [kg CO2/MWh]
            "ramping time": 15,  # [min]
            "lifespan": 1209600,  # [s]
            "requirements": [],
        },
        "windmill": {
            "price": 22200,
            "power generation": 3350000,
            "construction time": 21600,
            "construction power factor": 0.56,
            "construction pollution": 1600,
            "O&M cost": 0.054,
            "consumed resource": {"wind": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 2419200,
            "requirements": [],
        },
        "watermill": {
            "price": 15000,
            "power generation": 2700000,
            "construction time": 18000,
            "construction power factor": 0.48,
            "construction pollution": 2200,
            "O&M cost": 0.055,
            "consumed resource": {"water": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 3024000,
            "requirements": [],
        },
        "coal_burner": {
            "price": 105000,
            "power generation": 21000000,
            "construction time": 194400,
            "construction power factor": 0.28,
            "construction pollution": 1100000,
            "O&M cost": 0.095,
            "consumed resource": {"coal": 640},
            "pollution": 1664,
            "ramping time": 75,
            "lifespan": 3628800,
            "requirements": [
                ["mechanical_engineering", 1, False],
                ["thermodynamics", 1, False],
                ["warehouse", 1, False],
            ],
        },
        "oil_burner": {
            "price": 52000,
            "power generation": 8000000,
            "construction time": 43200,
            "construction power factor": 0.56,
            "construction pollution": 440000,
            "O&M cost": 0.1,
            "consumed resource": {"oil": 375},
            "pollution": 1181,
            "ramping time": 10,
            "lifespan": 2419200,
            "requirements": [
                ["mechanical_engineering", 1, False],
                ["thermodynamics", 1, False],
                ["warehouse", 1, False],
            ],
        },
        "gas_burner": {
            "price": 90000,
            "power generation": 11000000,
            "construction time": 43200,
            "construction power factor": 0.56,
            "construction pollution": 657000,
            "O&M cost": 0.117,
            "consumed resource": {"gas": 353},
            "pollution": 1006,
            "ramping time": 9,
            "lifespan": 2419200,
            "requirements": [
                ["mechanical_engineering", 1, False],
                ["thermodynamics", 1, False],
                ["warehouse", 1, False],
            ],
        },
        "small_water_dam": {
            "price": 45000,
            "power generation": 27500000,
            "construction time": 216000,
            "construction power factor": 0.3,
            "construction pollution": 876000,
            "O&M cost": 0.032,
            "consumed resource": {"hydropower": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 9072000,
            "requirements": [["civil_engineering", 1, False]],
        },
        "onshore_wind_turbine": {
            "price": 270000,
            "power generation": 11000000,
            "construction time": 64800,
            "construction power factor": 1.3,
            "construction pollution": 420000,
            "O&M cost": 0.052,
            "consumed resource": {"wind": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 3870720,
            "requirements": [
                ["aerodynamics", 1, False],
                ["materials", 2, False],
                ["mechanical_engineering", 3, False],
            ],
        },
        "combined_cycle": {
            "price": 310000,
            "power generation": 54000000,
            "construction time": 108000,
            "construction power factor": 0.56,
            "construction pollution": 1500000,
            "O&M cost": 0.102,
            "consumed resource": {"gas": 210, "coal": 76},
            "pollution": 797,
            "ramping time": 150,
            "lifespan": 4233600,
            "requirements": [
                ["thermodynamics", 3, False],
                ["mechanical_engineering", 3, False],
                ["warehouse", 2, False],
            ],
        },
        "nuclear_reactor": {
            "price": 840000,
            "power generation": 167000000,
            "construction time": 432000,
            "construction power factor": 0.08,
            "construction pollution": 6800000,
            "O&M cost": 0.104,
            "consumed resource": {"uranium": 0.044},
            "efficiency": 0.22,
            "pollution": 2,
            "ramping time": 1200,
            "lifespan": 6048000,
            "requirements": [
                ["chemistry", 3, False],
                ["nuclear_engineering", 1, False],
                ["warehouse", 3, False],
            ],
        },
        "large_water_dam": {
            "price": 320000,
            "power generation": 410000000,
            "construction time": 302400,
            "construction power factor": 0.15,
            "construction pollution": 8760000,
            "O&M cost": 0.022,
            "consumed resource": {"hydropower": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 12096000,
            "requirements": [["civil_engineering", 4, False]],
        },
        "CSP_solar": {
            "price": 123000,
            "power generation": 38000000,
            "construction time": 129600,
            "construction power factor": 0.4,
            "construction pollution": 1260000,
            "O&M cost": 0.067,
            "consumed resource": {"irradiation": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 2782080,
            "requirements": [
                ["physics", 5, False],
                ["thermodynamics", 5, False],
            ],
        },
        "PV_solar": {
            "price": 700000,
            "power generation": 59000000,
            "construction time": 32400,
            "construction power factor": 5,
            "construction pollution": 24000000,
            "O&M cost": 0.02,
            "consumed resource": {"irradiation": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 2177280,
            "requirements": [["physics", 6, False], ["materials", 4, False]],
        },
        "offshore_wind_turbine": {
            "price": 2000000,
            "power generation": 130000000,
            "construction time": 172800,
            "construction power factor": 1.2,
            "construction pollution": 4900000,
            "O&M cost": 0.065,
            "consumed resource": {"wind": 0},
            "pollution": 0,
            "ramping time": 0,
            "lifespan": 4596480,
            "requirements": [
                ["aerodynamics", 3, False],
                ["materials", 4, False],
                ["mechanical_engineering", 6, False],
            ],
        },
        "nuclear_reactor_gen4": {
            "price": 1800000,
            "power generation": 335000000,
            "construction time": 518400,
            "construction power factor": 0.06,
            "construction pollution": 12000000,
            "O&M cost": 0.085,
            "consumed resource": {"uranium": 0.00057},
            "efficiency": 0.3,
            "pollution": 3,
            "ramping time": 800,
            "lifespan": 8467200,
            "requirements": [
                ["chemistry", 5, False],
                ["nuclear_engineering", 5, False],
                ["warehouse", 3, False],
            ],
        },
        "small_pumped_hydro": {
            "price": 19500,  # [¤]
            "storage capacity": 260000000,  # [Wh]
            "power generation": 2600000,  # [W]
            "efficiency": 0.75,
            "construction time": 18720,  # [s]
            "construction power factor": 0.005,  # fraction of capacity demanded during construction
            "construction pollution": 80000,  # [kg]
            "O&M cost": 0.088,  # [fraction of price per year]
            "ramping time": 9,  # [min]
            "lifespan": 9072000,  # [s]
            "requirements": [],
        },
        "compressed_air": {
            "price": 10700,
            "storage capacity": 2860000000,
            "power generation": 12000000,
            "efficiency": 0.52,
            "construction time": 64800,
            "construction power factor": 0.001,
            "construction pollution": 570000,
            "O&M cost": 0.297,
            "ramping time": 5,
            "lifespan": 3265920,
            "requirements": [
                ["mechanical_engineering", 2, False],
                ["thermodynamics", 2, False],
            ],
        },
        "molten_salt": {
            "price": 27500,
            "storage capacity": 3000000000,
            "power generation": 55000000,
            "efficiency": 0.63,
            "construction time": 86400,
            "construction power factor": 0.001,
            "construction pollution": 1200000,
            "O&M cost": 0.424,
            "ramping time": 60,
            "lifespan": 1814400,
            "requirements": [
                ["mechanical_engineering", 2, False],
                ["thermodynamics", 3, False],
            ],
        },
        "large_pumped_hydro": {
            "price": 166000,
            "storage capacity": 4200000000,
            "power generation": 249000000,
            "efficiency": 0.8,
            "construction time": 334800,
            "construction power factor": 0.003,
            "construction pollution": 3000000,
            "O&M cost": 0.115,
            "ramping time": 16,
            "lifespan": 10886400,
            "requirements": [["civil_engineering", 3, False]],
        },
        "hydrogen_storage": {
            "price": 420000,
            "storage capacity": 30000000000,
            "power generation": 90000000,
            "efficiency": 0.33,
            "construction time": 43200,
            "construction power factor": 0.00025,
            "construction pollution": 2400000,
            "O&M cost": 0.028,
            "ramping time": 8,
            "lifespan": 5443200,
            "requirements": [["chemistry", 3, False], ["materials", 3, False]],
        },
        "lithium_ion_batteries": {
            "price": 660000,
            "storage capacity": 3200000000,
            "power generation": 86000000,
            "efficiency": 0.69,
            "construction time": 64800,
            "construction power factor": 0.1,
            "construction pollution": 8000000,
            "O&M cost": 0.003,
            "ramping time": 3,
            "lifespan": 967680,
            "requirements": [["chemistry", 4, False], ["materials", 4, False]],
        },
        "solid_state_batteries": {
            "price": 1000000,
            "storage capacity": 5000000000,
            "power generation": 107000000,
            "efficiency": 0.79,
            "construction time": 54000,
            "construction power factor": 0.07,
            "construction pollution": 6000000,
            "O&M cost": 0.002,
            "ramping time": 3,
            "lifespan": 1814400,
            "requirements": [
                ["chemistry", 6, False],
                ["materials", 5, False],
                ["physics", 6, False],
            ],
        },
        "laboratory": {
            "price": 32000,  # [¤]
            "construction time": 5400,  # [s]
            "construction energy": 750000,  # [Wh]
            "construction pollution": 100000,  # [kg]
            "requirements": [],
        },
        "warehouse": {
            "price": 25000,
            "construction time": 18000,
            "construction energy": 100000,
            "construction pollution": 25000,
            "requirements": [],
        },
        "industry": {
            "price": 2400,
            "construction time": 1200,
            "construction energy": 40000,
            "construction pollution": 4000,
            "power consumption": 200000,  # [W]
            "income": 8000,  # [¤/day]
            "requirements": [],
        },
        "carbon_capture": {
            "price": 250000,
            "construction time": 36000,
            "construction energy": 50000000,
            "construction pollution": 250000,
            "O&M cost": 0.7,
            "power consumption": 10000000,  # [W]
            "absorbtion": 2000,  # [kg/h]
            "requirements": [
                ["mathematics", 3, False],
                ["physics", 3, False],
                ["chemistry", 3, False],
            ],
        },
        "coal_mine": {
            "price": 28500,  # [¤]
            "construction time": 28800,  # [s]
            "construction power factor": 1.5,  # fraction of power consumption during construction
            "construction pollution": 200000,  # [kg]
            "O&M cost": 0.25,  # [fraction of price per year]
            "power consumption": 3000000,  # [W]
            "pollution": 0.065,  # [kg/kg extracted]
            "lifespan": 2782080,  # [s]
            "requirements": [
                ["mineral_extraction", 1, False],
                ["warehouse", 1, False],
            ],
        },
        "oil_field": {
            "price": 120000,
            "construction time": 54000,
            "construction power factor": 2,
            "construction pollution": 400000,
            "O&M cost": 0.36,
            "power consumption": 7300000,
            "pollution": 0.302,
            "lifespan": 1451520,
            "requirements": [
                ["mineral_extraction", 2, False],
                ["warehouse", 1, False],
            ],
        },
        "gas_drilling_site": {
            "price": 110000,
            "construction time": 54000,
            "construction power factor": 2.5,
            "construction pollution": 700000,
            "O&M cost": 0.36,
            "power consumption": 5100000,
            "pollution": 0.523,
            "lifespan": 1209600,
            "requirements": [
                ["mineral_extraction", 2, False],
                ["warehouse", 1, False],
            ],
        },
        "uranium_mine": {
            "price": 350000,
            "construction time": 86400,
            "construction power factor": 2,
            "construction pollution": 500000,
            "O&M cost": 0.5,
            "power consumption": 18000000,
            "pollution": 230,
            "lifespan": 2177280,
            "requirements": [
                ["mineral_extraction", 5, False],
                ["warehouse", 3, False],
            ],
        },
        "mathematics": {
            "price": 36000,  # [¤]
            "construction time": 18000,  # [s]
            "construction energy": 5000000,  # [Wh]
            "requirements": [
                ["laboratory", 1, False]
            ],  # level is given relative to the research level
        },
        "mechanical_engineering": {
            "price": 36000,
            "construction time": 18000,
            "construction energy": 5000000,
            "requirements": [
                ["laboratory", 1, False],
                ["mathematics", 1, False],
            ],
        },
        "thermodynamics": {
            "price": 36000,
            "construction time": 18000,
            "construction energy": 5000000,
            "requirements": [
                ["laboratory", 1, False],
                ["mathematics", 1, False],
            ],
        },
        "physics": {
            "price": 36000,
            "construction time": 18000,
            "construction energy": 5000000,
            "requirements": [
                ["laboratory", 1, False],
                ["mathematics", 1, False],
                ["chemistry", -2, False],
            ],
        },
        "building_technology": {
            "price": 56000,
            "construction time": 28800,
            "construction energy": 16000000,
            "requirements": [
                ["laboratory", 1, False],
                ["transport_technology", -2, False],
            ],
        },
        "mineral_extraction": {
            "price": 32000,
            "construction time": 14400,
            "construction energy": 8000000,
            "requirements": [
                ["laboratory", 1, False],
                ["mathematics", 1, False],
            ],
        },
        "transport_technology": {
            "price": 56000,
            "construction time": 28800,
            "construction energy": 24000000,
            "requirements": [
                ["laboratory", 2, False],
                ["mechanical_engineering", 1, False],
            ],
        },
        "materials": {
            "price": 84000,
            "construction time": 43200,
            "construction energy": 48000000,
            "requirements": [
                ["laboratory", 2, False],
                ["chemistry", 0, False],
            ],
        },
        "civil_engineering": {
            "price": 28000,
            "construction time": 14400,
            "construction energy": 16000000,
            "requirements": [
                ["laboratory", 3, False],
                ["mathematics", 2, False],
                ["building_technology", 2, False],
            ],
        },
        "aerodynamics": {
            "price": 84000,
            "construction time": 43200,
            "construction energy": 60000000,
            "requirements": [
                ["laboratory", 3, False],
                ["physics", 3, False],
            ],
        },
        "chemistry": {
            "price": 60000,
            "construction time": 28800,
            "construction energy": 40000000,
            "requirements": [
                ["laboratory", 3, False],
                ["physics", -1, False],
            ],
        },
        "nuclear_engineering": {
            "price": 140000,
            "construction time": 64800,
            "construction energy": 108000000,
            "requirements": [
                ["laboratory", 4, False],
                ["physics", 3, False],
                ["mechanical_engineering", 3, False],
            ],
        },
    },
    "warehouse_capacities": {
        "coal": 3000000 / 1.5,  # [kg]
        "oil": 300000 / 1.5,
        "gas": 1000000 / 1.5,
        "uranium": 5000 / 1.5,
    },
    "transport": {
        "time": 5000,  # [s/distance unit]
        "power consumption": 5,  # [Wh/kg/distance unit]
    },
}

wind_power_curve = [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.0013449,
    0.00821,
    0.015678,
    0.024249,
    0.034402,
    0.046221,
    0.059494,
    0.074,
    0.089609,
    0.10656,
    0.12518,
    0.14581,
    0.16863,
    0.19365,
    0.22089,
    0.25034,
    0.28197,
    0.31575,
    0.35165,
    0.38968,
    0.43003,
    0.4729,
    0.51844,
    0.56601,
    0.61438,
    0.6623,
    0.70858,
    0.75233,
    0.79272,
    0.82894,
    0.86076,
    0.88869,
    0.91332,
    0.93514,
    0.95407,
    0.96978,
    0.98193,
    0.99048,
    0.99602,
    0.99922,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0.8,
    0.6,
    0.4,
    0.2,
    0,
]  # from 0 to 100 km/h

river_discharge_seasonal = [
    0.26,
    0.23,
    0.3,
    0.5,
    0.85,
    1,
    0.96,
    0.85,
    0.55,
    0.4,
    0.35,
    0.3,
]  # from january to december


# config object that contains the modified data for a specific player considering the technologies he owns :
class Config(object):
    def __init__(config):
        config.for_player = {}

    # update mining speeds according to reserves depleation
    def update_resource_extraction(config, player_id):
        engine = current_app.config["engine"]
        player = Player.query.get(player_id)
        if player.tile is None:
            return
        assets = config.for_player[player_id]["assets"]
        me_factor = (
            const_config["assets"]["mineral_extraction"]["extract factor"]
            ** player.mineral_extraction
        )
        assets["coal_mine"]["amount produced"] = (
            const_config["assets"]["coal_mine"]["extraction_rate"]
            * player.tile.coal
            * me_factor
            * engine.clock_time
            / 60
        )
        assets["oil_field"]["amount produced"] = (
            const_config["assets"]["oil_field"]["extraction_rate"]
            * player.tile.oil
            * me_factor
            * engine.clock_time
            / 60
        )
        assets["gas_drilling_site"]["amount produced"] = (
            const_config["assets"]["gas_drilling_site"]["extraction_rate"]
            * player.tile.gas
            * me_factor
            * engine.clock_time
            / 60
        )
        assets["uranium_mine"]["amount produced"] = (
            const_config["assets"]["uranium_mine"]["extraction_rate"]
            * player.tile.uranium
            * me_factor
            * engine.clock_time
            / 60
        )

    # regularly update minimg productivity for all players (mineral depletion)
    def update_mining_productivity(config):
        players = Player.query.all()
        for player in players:
            if player in config.for_player:
                config.update_resource_extraction(player.id)

    # updating the config values according to the players technology level
    def update_config_for_user(config, player_id):
        engine = current_app.config["engine"]
        config.for_player[player_id] = copy.deepcopy(var_config)
        assets = config.for_player[player_id]["assets"]
        player = Player.query.get(player_id)
        config.update_resource_extraction(player_id)

        for asset in assets:
            

            if asset in engine.technologies:
                # remove fulfilled requirements
                assets[asset]["locked"] = False
                for req in assets[asset]["requirements"]:
                    if req[1] + getattr(player, asset) < 1:
                        assets[asset]["requirements"].remove(req)
                        continue
                    req[2] = getattr(player, req[0]) >= req[1] + getattr(
                        player, asset
                    )
                    if not req[2]:
                        assets[asset]["locked"] = True

            if asset == "industry":
                # calculating industry energy consumption and income
                assets[asset]["power consumption"] *= (
                    const_config["assets"]["industry"]["power factor"]
                    ** player.industry
                )
                assets[asset]["income"] *= (
                    const_config["assets"]["industry"]["income factor"]
                    ** player.industry
                )
                # basic universal income of 2000 per day
                assets[asset]["income"] += 2000

            if asset == "carbon_capture":
                # calculating carbon capture power consumption and CO2 absorbtion
                assets[asset]["power consumption"] *= (
                    const_config["assets"]["carbon_capture"]["power factor"]
                    ** player.carbon_capture
                )
                assets[asset]["absorbtion"] *= (
                    const_config["assets"]["carbon_capture"][
                        "absorbtion factor"
                    ]
                    ** player.carbon_capture
                )

            if (
                asset
                in engine.storage_facilities
                + engine.controllable_facilities
                + engine.renewables
                + engine.extraction_facilities
                + engine.functional_facilities
            ):
                # remove fulfilled requirements
                assets[asset]["locked"] = False
                for req in assets[asset]["requirements"]:
                    req[2] = getattr(player, req[0]) >= req[1]
                    if not req[2]:
                        assets[asset]["locked"] = True

                if asset not in ["industry", "laboratory", "warehouse"]:
                    # calculate O&M cost
                    assets[asset]["O&M cost"] *= assets[asset]["price"] / 1440

            # calculating the ramping speed in W/min from the ramping time
            if "ramping time" in assets[asset]:
                if assets[asset]["ramping time"] == 0:
                    assets[asset]["ramping speed"] = 0
                else:
                    assets[asset]["ramping speed"] = (
                        assets[asset]["power generation"]
                        / assets[asset]["ramping time"]
                        * engine.clock_time
                        / 60
                    )

            # calculate energy need :
            bt_factor = (
                const_config["assets"]["building_technology"]["time factor"]
                ** player.building_technology
            )
            if asset in engine.controllable_facilities + engine.renewables:
                assets[asset]["construction power"] = (
                    assets[asset]["construction power factor"]
                    * assets[asset]["power generation"]
                    / bt_factor
                )
            elif asset in engine.storage_facilities:
                assets[asset]["construction power"] = (
                    assets[asset]["construction power factor"]
                    * assets[asset]["storage capacity"]
                    / bt_factor
                )
            elif asset in engine.extraction_facilities:
                assets[asset]["construction power"] = (
                    assets[asset]["construction power factor"]
                    * assets[asset]["power consumption"]
                    / bt_factor
                )
            else:
                assets[asset]["construction power"] = (
                    assets[asset]["construction energy"]
                    / assets[asset]["construction time"]
                    * 60
                    * (60 * engine.clock_time) ** 0.5
                )

        # calculating the maximum storage capacity from the warehouse level
        max_cap = config.for_player[player_id]["warehouse_capacities"]
        for resource in max_cap:
            if player.warehouse == 0:
                max_cap[resource] = 0
            else:
                max_cap[resource] *= (
                    const_config["assets"]["warehouse"]["capacity factor"]
                    ** player.warehouse
                )

        # calculating the transport speed and energy consumption from the level of transport technology
        config.for_player[player_id]["transport"]["time"] *= (
            const_config["assets"]["transport_technology"]["time factor"]
            ** player.transport_technology
        )
        config.for_player[player_id]["transport"]["power consumption"] *= (
            const_config["assets"]["transport_technology"]["energy factor"]
            ** player.transport_technology
            * 3600
            / config.for_player[player_id]["transport"]["time"]
        )
        # reducing shipment time with clock time
        config.for_player[player_id]["transport"]["time"] *= (
            engine.clock_time / 60
        ) ** 0.5

        # setting the number of workers
        player.construction_workers = player.building_technology + 1
        player.lab_workers = (player.laboratory + 2) // 3

    def __getitem__(config, player_id):
        if player_id not in config.for_player:
            config.update_config_for_user(player_id)
        return config.for_player[player_id]


config = Config()
